# Generated by Django 2.1.4 on 2019-07-20 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('area_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
            },
        ),
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('phone_no', models.CharField(max_length=16)),
                ('lang', models.CharField(max_length=4)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Transport Provider',
                'verbose_name_plural': 'TransportProviders ',
            },
        ),
        migrations.AddField(
            model_name='servicearea',
            name='transport_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='service_areas', to='trans_providers.TransportProvider'),
        ),
    ]
