# Generated by Django 2.1.4 on 2019-07-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='area_polygon',
            new_name='poly',
        ),
    ]
