# Generated by Django 2.1.4 on 2019-07-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_providers', '0002_auto_20190721_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='poly',
            new_name='area_polygon',
        ),
    ]
